exports = module.exports = function(client) {
  
  return function challenge(authenticator, options, cb) {
    if (typeof options == 'function') {
      cb = options;
      options = undefined;
    }
    options = options || {};
    
    var type = options.type || 'otp'
      , channel = options.channel || 'sms';
    
    
    if (type == 'otp') {
      client.request_sms(authenticator._userID, function(err, res) {
        if (err) { return cb(err); }
        cb();
      });
    } else if (type == 'oob') {
      function telephonyComplete(err, res) {
        if (err) { return cb(err); }
        // TODO: Add confirmation method, oob code
        return cb(null, { type: 'oob', confirmation: { channel: 'primary' } });
      }
      
      
      // NOTE: Evidence suggests that the OTP codes sent via phone call or SMS
      //       are different than those generated by the Authy app on the same
      //       phone.  This demonstrates that security concerns have been
      //       properly considered, and the secret is not shared between
      //       logically independent parties.
      
      if (channel == 'sms') {
        // TODO: Use action parameter here to distinguish between SMS codes and device-generated codes?
        client.request_sms(authenticator._userID, true, telephonyComplete);
      } else if (channel == 'tel') {
        // TODO: Use action parameter here to distinguish between SMS codes and device-generated codes?
        client.request_call(authenticator._userID, true, telephonyComplete);
      } else {
        // TODO:
      }
    } else {
      // TODO: error
    }
  };
};

exports['@implements'] = [
  'http://schemas.authnomicon.org/js/login/mfa/challenge',
  'http://schemas.authnomicon.org/js/login/mfa/opt/authy/challenge'
];
exports['@singleton'] = true;
exports['@require'] = [
  'http://schemas.authnomicon.org/js/login/mfa/opt/authy/Client'
];
