exports = module.exports = function(client) {
  
  return function challenge(authenticator, options, cb) {
    if (typeof options == 'function') {
      cb = options;
      options = undefined;
    }
    options = options || {};
    
    var type = options.type || 'otp';
    
    
    // TODO: Other OTP transport mechanisms
    /*
    //authy.request_sms(authyID, true, function (err, res) {
    //authy.request_call(authyID, function (err, res) {
    //authy.request_call(authyID, true, function (err, res) {
    */
    
    if (type == 'otp') {
      client.request_sms(authenticator._userID, function(err, res) {
        if (err) { return cb(err); }
        cb();
      });
    } else if (type == 'oob') {
      // NOTE: Evidence suggests that the OTP codes sent via SMS are different
      //       than those generated by the Authy app on the same phone.  This
      //       demonstrates that security concerns have been properly
      //       considered, and the secret is not shared between logically
      //       separate parties.
      
      // TODO: Use action parameter here to distinguish between SMS codes and device-generated codes?
      client.request_sms(authenticator._userID, true, function(err, res) {
        if (err) { return cb(err); }
        // TODO: Add confirmation method, oob code
        cb(null, { type: 'oob' });
      });
      
    } else {
      // TODO: error
    }
  };
};

exports['@implements'] = [
  'http://schemas.authnomicon.org/js/login/mfa/challenge',
  'http://schemas.authnomicon.org/js/login/mfa/opt/authy/challenge'
];
exports['@singleton'] = true;
exports['@require'] = [
  'http://schemas.authnomicon.org/js/login/mfa/opt/authy/Client'
];
